import type { Tour, Review } from '../types'
import { INDIAN_DESTINATIONS } from './indianDestinations'

export const INDIAN_TOURS: Tour[] = [
  {
    _id: 't1', title: 'Golden Triangle Heritage Trail', slug: 'golden-triangle-heritage',
    destination: INDIAN_DESTINATIONS[0],
    description: 'Explore India\'s iconic Golden Triangle — Delhi, Agra and Jaipur. Witness the Taj Mahal at sunrise, explore the mighty Amber Fort, wander through Old Delhi\'s spice-scented lanes and experience the grandeur of Mughal and Rajput architecture.',
    shortDescription: 'Delhi → Agra → Jaipur — Taj Mahal, forts & royal palaces.',
    coverImage: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80'],
    price: 18900, discountPrice: 15900, duration: 7, groupSize: { min: 4, max: 16 },
    difficulty: 'easy', category: 'cultural',
    includes: ['Heritage hotels','Daily breakfast','Expert guide','All monument entries','AC transport','Airport transfers'],
    excludes: ['Flights','Travel insurance','Lunches & dinners','Personal expenses'],
    highlights: ['Taj Mahal Sunrise','Amber Fort Elephant Ride','Old Delhi Food Walk','Hawa Mahal','Fatehpur Sikri'],
    itinerary: [
      { day: 1, title: 'Arrive Delhi', description: 'Airport pickup, check into heritage hotel, evening at India Gate.', activities: ['Airport transfer','India Gate','Welcome dinner'] },
      { day: 2, title: 'Old & New Delhi', description: 'Red Fort, Jama Masjid, Chandni Chowk food walk, Humayun Tomb.', activities: ['Red Fort','Jama Masjid','Chandni Chowk','Humayun Tomb'] },
    ],
    rating: 4.9, reviewCount: 420, isFeatured: true, isAvailable: true,
    startDates: ['2025-10-15','2025-11-12','2025-12-09','2026-01-10'],
    guide: { _id: 'g1', name: 'Rajesh Sharma', email: 'rajesh@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=100&q=80' },
    createdAt: '2024-01-01',
  },
  {
    _id: 't2', title: 'Kerala Backwater Bliss', slug: 'kerala-backwater-bliss',
    destination: INDIAN_DESTINATIONS[2],
    description: 'Drift through Kerala\'s palm-fringed backwaters on a luxury houseboat, learn authentic Kerala cooking, experience a traditional Ayurvedic spa, watch Kathakali dancers and trek through Munnar tea plantations.',
    shortDescription: 'Houseboats, Ayurveda, Kathakali & tea plantation treks.',
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80'],
    price: 22500, duration: 8, groupSize: { min: 2, max: 10 },
    difficulty: 'easy', category: 'cultural',
    includes: ['Luxury houseboat','All meals on boat','Ayurveda session','Kathakali show','Munnar guide','Cochin transfers'],
    excludes: ['Flights','Insurance','Personal expenses'],
    highlights: ['Alleppey Houseboat Overnight','Munnar Tea Gardens','Kathakali Performance','Cochin Fort Kochi Walk','Ayurvedic Spa Day'],
    itinerary: [], rating: 4.8, reviewCount: 310, isFeatured: true, isAvailable: true,
    startDates: ['2025-09-20','2025-11-05','2026-01-15'],
    guide: { _id: 'g2', name: 'Priya Nair', email: 'priya@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80' },
    createdAt: '2024-01-02',
  },
  {
    _id: 't3', title: 'Ladakh Motorcycle Expedition', slug: 'ladakh-motorcycle-expedition',
    destination: INDIAN_DESTINATIONS[4],
    description: 'The ultimate Indian road trip — ride Royal Enfields over the world\'s highest motorable passes, camp beside Pangong Lake, visit ancient monasteries and cross the dramatic Zanskar range.',
    shortDescription: 'Royal Enfield across the highest passes — Pangong, Khardung La & beyond.',
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80'],
    price: 35000, duration: 12, groupSize: { min: 6, max: 12 },
    difficulty: 'challenging', category: 'adventure',
    includes: ['Royal Enfield rental','Fuel','Camping gear','All meals','Mechanic support','Leh hotel'],
    excludes: ['Flights to Leh','Insurance','Personal gear','Riding gear rental'],
    highlights: ['Khardung La Pass','Pangong Lake Camping','Nubra Valley','Magnetic Hill','Thiksey Monastery'],
    itinerary: [], rating: 4.9, reviewCount: 280, isFeatured: true, isAvailable: true,
    startDates: ['2025-06-15','2025-07-20','2025-08-18'],
    guide: { _id: 'g3', name: 'Tenzin Dorjee', email: 'tenzin@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80' },
    createdAt: '2024-01-03',
  },
  {
    _id: 't4', title: 'Rajasthan Royal Safari', slug: 'rajasthan-royal-safari',
    destination: INDIAN_DESTINATIONS[3],
    description: 'Live like royalty across Rajasthan — stay in heritage havelis and palace hotels, ride camels across the Thar Desert dunes, explore the mighty Mehrangarh Fort in Jodhpur and watch sunset from Jaisalmer Fort.',
    shortDescription: 'Palace hotels, camel safaris & mighty desert forts.',
    coverImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80'],
    price: 28000, duration: 10, groupSize: { min: 4, max: 14 },
    difficulty: 'easy', category: 'cultural',
    includes: ['Heritage palace hotels','Breakfast daily','Camel safari','All fort entries','AC vehicle','Expert guide'],
    excludes: ['Flights','Insurance','Lunches & dinners','Shopping'],
    highlights: ['Jaisalmer Desert Camp','Mehrangarh Fort','Udaipur Lake Palace','Pushkar Camel Fair','Jodhpur Blue City Walk'],
    itinerary: [], rating: 4.8, reviewCount: 350, isFeatured: true, isAvailable: true,
    startDates: ['2025-10-01','2025-11-15','2025-12-20','2026-02-10'],
    guide: { _id: 'g4', name: 'Vikram Singh', email: 'vikram@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80' },
    createdAt: '2024-01-04',
  },
  {
    _id: 't5', title: 'Goa Beach & Beyond', slug: 'goa-beach-beyond',
    destination: INDIAN_DESTINATIONS[1],
    description: 'More than beaches — explore Goa\'s Portuguese heritage churches, spice plantations, Dudhsagar waterfall trek, dolphin cruises and the vibrant night markets of Anjuna and Arpora.',
    shortDescription: 'Beaches, heritage churches, spice farms & Dudhsagar falls.',
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80'],
    price: 12500, duration: 5, groupSize: { min: 2, max: 12 },
    difficulty: 'easy', category: 'beach',
    includes: ['Beach resort','Breakfast','Dudhsagar trek guide','Dolphin cruise','Spice plantation tour'],
    excludes: ['Flights','Insurance','Lunches & dinners','Water sports'],
    highlights: ['Palolem Beach','Basilica of Bom Jesus','Dudhsagar Falls','Spice Plantation','Anjuna Flea Market'],
    itinerary: [], rating: 4.7, reviewCount: 450, isFeatured: true, isAvailable: true,
    startDates: ['2025-11-01','2025-12-15','2026-01-20','2026-02-15'],
    guide: { _id: 'g5', name: 'Marco Fernandes', email: 'marco@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80' },
    createdAt: '2024-01-05',
  },
  {
    _id: 't6', title: 'Varanasi Spiritual Immersion', slug: 'varanasi-spiritual-immersion',
    destination: INDIAN_DESTINATIONS[5],
    description: 'Experience the raw spiritual power of India\'s holiest city. Witness the grand Ganga Aarti, take a dawn boat ride past the ancient ghats, visit Sarnath where Buddha preached his first sermon, and learn the art of silk weaving.',
    shortDescription: 'Ganga Aarti, dawn boat ride, Sarnath & ancient silk weaving.',
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80'],
    price: 9500, duration: 4, groupSize: { min: 2, max: 10 },
    difficulty: 'easy', category: 'cultural',
    includes: ['Heritage hotel','Breakfast','Ganga Aarti VIP seat','Boat ride','Sarnath guide','Silk factory visit'],
    excludes: ['Flights','Insurance','Other meals'],
    highlights: ['Ganga Aarti Ceremony','Dawn Boat Ride','Sarnath Buddhist Site','Silk Weaving Workshop','Kashi Vishwanath Temple'],
    itinerary: [], rating: 4.7, reviewCount: 200, isFeatured: false, isAvailable: true,
    startDates: ['2025-10-20','2025-11-15','2026-01-10'],
    guide: { _id: 'g6', name: 'Anand Mishra', email: 'anand@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=100&q=80' },
    createdAt: '2024-01-06',
  },
  {
    _id: 't7', title: 'Andaman Dive & Explore', slug: 'andaman-dive-explore',
    destination: INDIAN_DESTINATIONS[6],
    description: 'Dive into crystal-clear waters of Havelock Island, snorkel over vibrant coral reefs, kayak through mangrove forests and relax on Radhanagar — one of Asia\'s finest beaches.',
    shortDescription: 'Scuba diving, coral reefs, mangrove kayaking & Radhanagar Beach.',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80'],
    price: 32000, duration: 6, groupSize: { min: 2, max: 8 },
    difficulty: 'moderate', category: 'adventure',
    includes: ['Beach resort','All meals','2 scuba dives','Snorkeling gear','Mangrove kayak','Ferry transfers'],
    excludes: ['Flights to Port Blair','Insurance','Extra dives'],
    highlights: ['Scuba at Elephant Beach','Radhanagar Beach','Mangrove Kayaking','Ross Island History Tour','Bioluminescent Beach Night'],
    itinerary: [], rating: 4.8, reviewCount: 180, isFeatured: true, isAvailable: true,
    startDates: ['2025-11-10','2025-12-20','2026-02-05'],
    guide: { _id: 'g7', name: 'Deepak Kumar', email: 'deepak@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80' },
    createdAt: '2024-01-07',
  },
  {
    _id: 't8', title: 'Rishikesh Adventure Retreat', slug: 'rishikesh-adventure-retreat',
    destination: INDIAN_DESTINATIONS[10],
    description: 'Adrenaline meets spirituality — raft Grade IV rapids on the Ganges, bungee jump from 83 meters, practice yoga at a riverside ashram and trek through the Himalayan foothills.',
    shortDescription: 'Rafting, bungee jumping, yoga & Himalayan trekking.',
    coverImage: 'https://images.unsplash.com/photo-1583396082781-89ef7a841c72?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1583396082781-89ef7a841c72?w=800&q=80'],
    price: 11000, duration: 4, groupSize: { min: 4, max: 16 },
    difficulty: 'moderate', category: 'adventure',
    includes: ['Riverside camp','All meals','Rafting','Bungee jump','Yoga sessions','Trekking guide'],
    excludes: ['Transport to Rishikesh','Insurance','Personal gear'],
    highlights: ['Grade IV Rafting','83m Bungee Jump','Sunrise Yoga by Ganges','Beatles Ashram','Laxman Jhula Walk'],
    itinerary: [], rating: 4.7, reviewCount: 320, isFeatured: false, isAvailable: true,
    startDates: ['2025-09-15','2025-10-20','2026-03-10'],
    guide: { _id: 'g8', name: 'Sunil Rawat', email: 'sunil@pavilion.travel', role: 'guide', createdAt: '2023-01-01', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80' },
    createdAt: '2024-01-08',
  },
]

export const INDIAN_REVIEWS: Review[] = [
  {
    _id: 'r1', tour: 't1',
    user: { _id: 'u1', name: 'Ananya Gupta', email: 'ananya@example.com', role: 'user', createdAt: '2024-01-01', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80' },
    rating: 5, title: 'The Taj at sunrise changed me forever',
    body: 'Seeing the Taj Mahal materialise out of the morning mist with Rajesh\'s expert narration about Shah Jahan\'s love story was genuinely one of the most moving experiences of my life. The entire Golden Triangle itinerary was flawlessly planned.',
    helpful: 67, createdAt: '2024-09-12',
  },
  {
    _id: 'r2', tour: 't3',
    user: { _id: 'u2', name: 'Arjun Mehta', email: 'arjun@example.com', role: 'user', createdAt: '2024-01-01', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80' },
    rating: 5, title: 'Ladakh is another planet — and this trip does it justice',
    body: 'Riding a Royal Enfield over Khardung La at 18,380 feet, then camping under a billion stars at Pangong Lake. Tenzin was an incredible guide who knew every secret spot. The mechanical support team saved us twice! Best trip of my life.',
    helpful: 83, createdAt: '2024-08-05',
  },
  {
    _id: 'r3', tour: 't2',
    user: { _id: 'u3', name: 'Sarah Mitchell', email: 'sarah@example.com', role: 'user', createdAt: '2024-01-01', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80' },
    rating: 5, title: 'Kerala is what heaven looks like',
    body: 'Waking up on a houseboat drifting through the backwaters, the morning mist rising off the water, coconut palms silhouetted against the sunrise — it was like being inside a painting. The Ayurvedic massage and Kathakali show were wonderful bonuses.',
    helpful: 52, createdAt: '2024-11-20',
  },
  {
    _id: 'r4', tour: 't4',
    user: { _id: 'u4', name: 'David Chen', email: 'david@example.com', role: 'user', createdAt: '2024-01-01', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80' },
    rating: 5, title: 'Rajasthan is a living fairy tale',
    body: 'Sleeping in a 400-year-old haveli, watching sunset from Jaisalmer Fort, riding a camel across the Thar Desert dunes under a sky carpeted with stars — Vikram brought Rajasthan\'s history alive at every stop. Pure magic.',
    helpful: 71, createdAt: '2024-07-30',
  },
]
