import type { Destination } from '../types'

export const INDIAN_DESTINATIONS: Destination[] = [
  {
    _id: 'd1', name: 'Taj Mahal, Agra', country: 'India', continent: 'North India',
    description: 'The crown jewel of India — an ivory-white marble mausoleum on the banks of the Yamuna. A UNESCO World Heritage Site and one of the Seven Wonders of the World, built by Mughal Emperor Shah Jahan as a testament to eternal love.',
    shortDescription: 'Ivory marble wonder — eternal monument to love on the Yamuna.',
    images: ['https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80','https://images.unsplash.com/photo-1585135497273-1a86d9d9e7ae?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80',
    rating: 4.9, reviewCount: 3200, category: ['cultural','city'],
    climate: 'Semi-arid', bestTimeToVisit: 'October – March', currency: 'INR', language: 'Hindi / Urdu',
    isFeatured: true, popularActivities: ['Taj Mahal Sunrise','Agra Fort','Fatehpur Sikri','Mehtab Bagh'], createdAt: '2024-01-01',
  },
  {
    _id: 'd2', name: 'Goa Beaches', country: 'India', continent: 'West India',
    description: 'India\'s smallest state packs the biggest punch — golden beaches, Portuguese heritage churches, vibrant nightlife, spice plantations and seafood shacks lining the Arabian Sea coast.',
    shortDescription: 'Sun, sand & soul — golden beaches meet Portuguese charm.',
    images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80','https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80',
    rating: 4.7, reviewCount: 2800, category: ['beach','adventure'],
    climate: 'Tropical', bestTimeToVisit: 'November – February', currency: 'INR', language: 'Konkani / English',
    isFeatured: true, popularActivities: ['Beach Hopping','Water Sports','Old Goa Churches','Dudhsagar Falls'], createdAt: '2024-01-02',
  },
  {
    _id: 'd3', name: 'Kerala Backwaters', country: 'India', continent: 'South India',
    description: 'God\'s Own Country — a network of tranquil lagoons, canals and lakes fringed by swaying palms. Drift through on a traditional houseboat, watch the emerald rice paddies and experience Ayurvedic wellness at its source.',
    shortDescription: 'God\'s Own Country — houseboats, palm-fringed lagoons & Ayurveda.',
    images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80','https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80',
    rating: 4.8, reviewCount: 2100, category: ['cultural','beach'],
    climate: 'Tropical', bestTimeToVisit: 'September – March', currency: 'INR', language: 'Malayalam',
    isFeatured: true, popularActivities: ['Houseboat Cruise','Ayurveda Spa','Kathakali Dance','Tea Plantation Trek'], createdAt: '2024-01-03',
  },
  {
    _id: 'd4', name: 'Jaipur, Rajasthan', country: 'India', continent: 'North India',
    description: 'The Pink City — a vibrant tapestry of majestic forts, ornate palaces, bustling bazaars and Rajasthani hospitality. Amber Fort, Hawa Mahal, City Palace and the energy of Johari Bazaar make this a photographer\'s paradise.',
    shortDescription: 'The Pink City — forts, palaces, bazaars & royal Rajasthani heritage.',
    images: ['https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&q=80','https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=1200&q=80',
    rating: 4.8, reviewCount: 2600, category: ['cultural','city'],
    climate: 'Semi-arid', bestTimeToVisit: 'October – March', currency: 'INR', language: 'Hindi / Rajasthani',
    isFeatured: true, popularActivities: ['Amber Fort','Hawa Mahal','City Palace','Nahargarh Fort Sunset'], createdAt: '2024-01-04',
  },
  {
    _id: 'd5', name: 'Leh Ladakh', country: 'India', continent: 'North India',
    description: 'The rooftop of India — a high-altitude desert of turquoise lakes, ancient Buddhist monasteries, dramatic mountain passes and landscapes that look like another planet. Pangong Lake alone will take your breath away.',
    shortDescription: 'Rooftop of India — turquoise lakes, monasteries & lunar landscapes.',
    images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80','https://images.unsplash.com/photo-1589556763229-ea5cee1f7925?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80',
    rating: 4.9, reviewCount: 1900, category: ['mountain','adventure'],
    climate: 'Alpine Desert', bestTimeToVisit: 'June – September', currency: 'INR', language: 'Ladakhi / Hindi',
    isFeatured: true, popularActivities: ['Pangong Lake','Khardung La Pass','Thiksey Monastery','Nubra Valley'], createdAt: '2024-01-05',
  },
  {
    _id: 'd6', name: 'Varanasi', country: 'India', continent: 'North India',
    description: 'The oldest living city in the world — where life and death coexist on the ghats of the sacred Ganges. The evening Ganga Aarti is one of the most powerful spiritual experiences on Earth.',
    shortDescription: 'Oldest living city — sacred ghats, Ganga Aarti & spiritual awakening.',
    images: ['https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1200&q=80','https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1200&q=80',
    rating: 4.7, reviewCount: 1800, category: ['cultural','city'],
    climate: 'Humid Subtropical', bestTimeToVisit: 'October – March', currency: 'INR', language: 'Hindi / Bhojpuri',
    isFeatured: false, popularActivities: ['Ganga Aarti','Boat Ride at Dawn','Sarnath Excursion','Silk Weaving'], createdAt: '2024-01-06',
  },
  {
    _id: 'd7', name: 'Andaman Islands', country: 'India', continent: 'Islands',
    description: 'Crystal-clear turquoise waters, pristine white sand beaches, world-class coral reefs and dense tropical rainforests. Radhanagar Beach on Havelock Island is regularly ranked among the best beaches in Asia.',
    shortDescription: 'Tropical paradise — crystal waters, coral reefs & pristine beaches.',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80','https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    rating: 4.8, reviewCount: 1400, category: ['beach','adventure'],
    climate: 'Tropical', bestTimeToVisit: 'November – April', currency: 'INR', language: 'Hindi / Bengali / Tamil',
    isFeatured: true, popularActivities: ['Scuba Diving','Radhanagar Beach','Mangrove Kayaking','Ross Island'], createdAt: '2024-01-07',
  },
  {
    _id: 'd8', name: 'Manali', country: 'India', continent: 'North India',
    description: 'A Himalayan jewel in Himachal Pradesh — snow-capped peaks, pine forests, apple orchards and the mighty Beas River. The gateway to Rohtang Pass and Solang Valley for adventure lovers.',
    shortDescription: 'Himalayan jewel — snow peaks, pine forests & adventure trails.',
    images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80','https://images.unsplash.com/photo-1585136917345-88d573e01e86?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80',
    rating: 4.7, reviewCount: 2200, category: ['mountain','adventure'],
    climate: 'Alpine', bestTimeToVisit: 'March – June / Oct – Feb', currency: 'INR', language: 'Hindi / Pahari',
    isFeatured: false, popularActivities: ['Rohtang Pass','Solang Valley','Old Manali','Beas River Rafting'], createdAt: '2024-01-08',
  },
  {
    _id: 'd9', name: 'Udaipur', country: 'India', continent: 'North India',
    description: 'The Venice of the East — a romantic city of shimmering lakes, white marble palaces and lush hills. Lake Pichola, City Palace and the Jag Mandir island palace create a fairy-tale setting.',
    shortDescription: 'Venice of the East — lakes, white palaces & Rajput romance.',
    images: ['https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=1200&q=80','https://images.unsplash.com/photo-1585136917345-88d573e01e86?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=1200&q=80',
    rating: 4.8, reviewCount: 1700, category: ['cultural','city'],
    climate: 'Semi-arid', bestTimeToVisit: 'September – March', currency: 'INR', language: 'Hindi / Mewari',
    isFeatured: false, popularActivities: ['Lake Pichola Boat Ride','City Palace','Jag Mandir','Monsoon Palace Sunset'], createdAt: '2024-01-09',
  },
  {
    _id: 'd10', name: 'Darjeeling', country: 'India', continent: 'East India',
    description: 'The Queen of Hills — endless tea gardens cascading down misty slopes, with Kanchenjunga towering above. Ride the UNESCO toy train, sip the world\'s finest tea, and watch the sunrise from Tiger Hill.',
    shortDescription: 'Queen of Hills — tea gardens, toy train & Kanchenjunga views.',
    images: ['https://images.unsplash.com/photo-1506038634487-60a69ae4b7b1?w=1200&q=80','https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1506038634487-60a69ae4b7b1?w=1200&q=80',
    rating: 4.6, reviewCount: 1500, category: ['mountain','cultural'],
    climate: 'Temperate', bestTimeToVisit: 'March – May / Oct – Dec', currency: 'INR', language: 'Nepali / Hindi / Bengali',
    isFeatured: false, popularActivities: ['Tiger Hill Sunrise','Toy Train Ride','Tea Garden Tour','Batasia Loop'], createdAt: '2024-01-10',
  },
  {
    _id: 'd11', name: 'Rishikesh', country: 'India', continent: 'North India',
    description: 'The Yoga Capital of the World — nestled in the Himalayan foothills where the Ganges roars through. White-water rafting, bungee jumping, ashrams and the iconic Laxman Jhula suspension bridge.',
    shortDescription: 'Yoga Capital — Ganges rapids, ashrams & Himalayan adventure.',
    images: ['https://images.unsplash.com/photo-1583396082781-89ef7a841c72?w=1200&q=80','https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1583396082781-89ef7a841c72?w=1200&q=80',
    rating: 4.7, reviewCount: 1900, category: ['adventure','cultural'],
    climate: 'Subtropical', bestTimeToVisit: 'Sept – Nov / Feb – May', currency: 'INR', language: 'Hindi',
    isFeatured: false, popularActivities: ['White-water Rafting','Bungee Jumping','Yoga Ashram','Laxman Jhula'], createdAt: '2024-01-11',
  },
  {
    _id: 'd12', name: 'Hampi', country: 'India', continent: 'South India',
    description: 'A surreal landscape of giant boulders and ancient Vijayanagara Empire ruins. UNESCO World Heritage Site with stunning stone-carved temples, royal enclosures and the iconic stone chariot at Vittala Temple.',
    shortDescription: 'Boulder kingdom — ancient ruins of the Vijayanagara Empire.',
    images: ['https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&q=80','https://images.unsplash.com/photo-1600100397608-ef8947f19383?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=1200&q=80',
    rating: 4.7, reviewCount: 1200, category: ['cultural','adventure'],
    climate: 'Semi-arid', bestTimeToVisit: 'October – February', currency: 'INR', language: 'Kannada / Hindi',
    isFeatured: false, popularActivities: ['Vittala Temple','Matanga Hill Sunrise','Coracle Ride','Boulder Climbing'], createdAt: '2024-01-12',
  },
  {
    _id: 'd13', name: 'Jaisalmer', country: 'India', continent: 'North India',
    description: 'The Golden City — a living fort rising from the Thar Desert like a mirage. Golden sandstone havelis, camel safaris across vast dunes, and starlit nights in desert camps.',
    shortDescription: 'Golden City — desert fort, sand dunes & starlit camel safaris.',
    images: ['https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80','https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80',
    rating: 4.8, reviewCount: 1600, category: ['desert','cultural'],
    climate: 'Arid', bestTimeToVisit: 'October – March', currency: 'INR', language: 'Hindi / Rajasthani',
    isFeatured: true, popularActivities: ['Desert Camel Safari','Jaisalmer Fort','Sam Sand Dunes','Patwon ki Haveli'], createdAt: '2024-01-13',
  },
  {
    _id: 'd14', name: 'Munnar', country: 'India', continent: 'South India',
    description: 'A hill station in Kerala draped in endless carpets of tea plantations. Rolling green hills, misty mornings, rare Neelakurinji flowers (bloom once every 12 years) and the highest peak in South India — Anamudi.',
    shortDescription: 'Emerald tea country — misty hills, spice gardens & Neelakurinji blooms.',
    images: ['https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=80','https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&q=80',
    rating: 4.7, reviewCount: 1300, category: ['mountain','cultural'],
    climate: 'Tropical Highland', bestTimeToVisit: 'September – May', currency: 'INR', language: 'Malayalam / Tamil',
    isFeatured: false, popularActivities: ['Tea Plantation Walk','Eravikulam National Park','Top Station','Mattupetty Dam'], createdAt: '2024-01-14',
  },
  {
    _id: 'd15', name: 'Kaziranga', country: 'India', continent: 'East India',
    description: 'Home to two-thirds of the world\'s one-horned rhinoceroses. This UNESCO World Heritage Site in Assam is a wildlife paradise with elephants, tigers, wild water buffalo and over 480 species of birds.',
    shortDescription: 'Rhino kingdom — UNESCO wildlife sanctuary in the heart of Assam.',
    images: ['https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200&q=80','https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80'],
    coverImage: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200&q=80',
    rating: 4.6, reviewCount: 900, category: ['wildlife','adventure'],
    climate: 'Tropical Monsoon', bestTimeToVisit: 'November – April', currency: 'INR', language: 'Assamese / Hindi',
    isFeatured: false, popularActivities: ['Elephant Safari','Jeep Safari','Bird Watching','Brahmaputra River Cruise'], createdAt: '2024-01-15',
  },
]
